dataset: "datasets/agaricus-lepiota.data"
nn:
  enabled: True               # Enable use of neural networks
  train: True                 # Enable training of NN, if disabled used model from <model_dir>
  test: True                  # Enable testing of NN
  model_dir: "models/nn/nn.model"
  conf_mat_dir: "models/nn/confusion_mat.yaml"
  parameters:
    neurons: 150                # Limits of neurons random generation (per layer)
    epochs: 500                 # Limits of epochs random generation (total)
    learning_rate: 0.01         # Limits of learning rate random gen
  error_threshold: 0.01         # Error threshold for stopping model generation
  avg_factor: 5