dataset: "datasets/art_digits.csv"
nn:
  enabled: True               # Enable use of neural networks
  train: True                 # Enable training of NN, if disabled used model from <model_dir>
  test: True                  # Enable testing of NN
  model_dir: "models/nn/"
  model_name: ""
  save_epoch: 100
  parameters:
    neurons: 10                # Limits of neurons random generation (per layer)
    epochs: 150                 # Limits of epochs random generation (total)
    learning_rate: 0.2         # Limits of learning rate random gen
  error_threshold: 0.01         # Error threshold for stopping model generation
  avg_factor: 5
svm:
  enabled: True
  train: True
  test: True
  model_dir: "models/svm/"
  model_name: ""
  C: 1.
  kernel: 'rbf'
  gamma: 1.
