two_spiral:
  dataset: "datasets/spiralsdataset.csv"
  training:
    nn:
      enabled: False
      epochs: 8000
      learning_rate: 0.8
      neurons: 50
    svm:
      enabled: True
      C: 0.5
      kernel: 'sigmoid'
      gamma: 0.001
  testing: 
    limits: [-7, 7]
  plotting:
    c1_colours: ['#ff00f6', '#ffbafc']
    c2_colours: ['#00e1ff', '#c9f8ff']